[SYCL][HIP] Ignore unused PI command-buffer parameters (#10192)
Fixes error found in [post-commit
CI](https://github.com/intel/llvm/actions/runs/5454766342/jobs/9925392005)
after the merge of https://github.com/intel/llvm/pull/9992

```
 /__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5635:24: error: unused parameter 'sync_point' [-Werror,-Wunused-parameter]
 5635 |     pi_ext_sync_point *sync_point) {
      |                        ^
/__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5691:12: error: unused parameter 'dst_row_pitch' [-Werror,-Wunused-parameter]
 5691 |     size_t dst_row_pitch, size_t dst_slice_pitch,
      |            ^
/__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5691:34: error: unused parameter 'dst_slice_pitch' [-Werror,-Wunused-parameter]
 5691 |     size_t dst_row_pitch, size_t dst_slice_pitch,
      |                                  ^
3 errors generated.
```